### ISSUE TITLE
ShineYourEye lookup no longer works

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician-scrapers/nigeria-state-governors#3]
This scraper is failing its run every day as the `id_to_pombola_data` lookup is failing due to http://www.shineyoureye.org/media_root/popolo_json/persons.json no longer existing.

**Comment by tmtmtmtm** [comment]
For now I've disabled the scraper.

**Comment by mhl** [comment]
This could be changed to http://pombola.shineyoureye.org/media_root/popolo_json/persons.json to get the scraper working again, although of course that data source is not being updated at the moment.

**Comment by mhl** [comment]
I've made this change now because rebuilding the images for ShineYourEye is dependent on this scraper producing some output: 3a01a08b36efedb23331
